# Generated by Django 5.1.4 on 2026-08-04 00:07

import apps.common.storages
import apps.planes.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('entities', '0006_entity_secop_nits'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PlanActividad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anio', models.IntegerField(db_index=True)),
                ('trimestre', models.PositiveSmallIntegerField(choices=[(1, 'Trimestre I'), (2, 'Trimestre II'), (3, 'Trimestre III'), (4, 'Trimestre IV')], db_index=True)),
                ('nombre', models.CharField(max_length=512)),
                ('descripcion', models.TextField(blank=True, default='')),
                ('meta', models.CharField(blank=True, default='', max_length=512)),
                ('indicador', models.CharField(blank=True, default='', max_length=512)),
                ('fecha_inicio', models.DateField(blank=True, null=True)),
                ('fecha_fin', models.DateField(blank=True, null=True)),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('EN_PROGRESO', 'En progreso'), ('COMPLETADA', 'Completada'), ('CANCELADA', 'Cancelada')], default='PENDIENTE', max_length=64)),
                ('avance', models.PositiveSmallIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('entity', models.ForeignKey(db_column='entity_id', on_delete=django.db.models.deletion.CASCADE, related_name='planes_actividades', to='entities.entity')),
                ('responsable_secretaria', models.ForeignKey(blank=True, db_column='responsable_secretaria_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='planes_actividades_responsable', to='entities.secretaria')),
                ('responsable_usuario', models.ForeignKey(blank=True, db_column='responsable_usuario_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='planes_actividades_responsable_usuario', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Actividad de plan institucional',
                'verbose_name_plural': 'Actividades de planes institucionales',
                'db_table': 'planes_actividades',
                'ordering': ['trimestre', 'fecha_inicio', 'id'],
            },
        ),
        migrations.CreateModel(
            name='PlanCatalogo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(db_index=True, max_length=64)),
                ('nombre', models.CharField(max_length=512)),
                ('orden', models.PositiveSmallIntegerField(default=0)),
                ('es_decreto612', models.BooleanField(default=False)),
                ('descripcion', models.TextField(blank=True, default='')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('entity', models.ForeignKey(blank=True, db_column='entity_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='planes_catalogo', to='entities.entity')),
            ],
            options={
                'verbose_name': 'Catálogo de plan institucional',
                'verbose_name_plural': 'Catálogo de planes institucionales',
                'db_table': 'planes_catalogo',
                'ordering': ['orden', 'nombre'],
            },
        ),
        migrations.CreateModel(
            name='PlanEvidencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.TextField()),
                ('url_evidencia', models.CharField(blank=True, max_length=1024, null=True)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('actividad', models.OneToOneField(db_column='actividad_id', on_delete=django.db.models.deletion.CASCADE, related_name='evidencia', to='planes.planactividad')),
                ('entity', models.ForeignKey(db_column='entity_id', on_delete=django.db.models.deletion.CASCADE, related_name='planes_evidencias', to='entities.entity')),
            ],
            options={
                'verbose_name': 'Evidencia de plan',
                'verbose_name_plural': 'Evidencias de planes',
                'db_table': 'planes_evidencias',
            },
        ),
        migrations.CreateModel(
            name='PlanEvidenciaArchivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archivo', models.FileField(max_length=500, storage=apps.common.storages.planes_file_storage, upload_to=apps.planes.models.plan_evidencia_archivo_upload_path)),
                ('nombre_original', models.CharField(blank=True, default='', max_length=255)),
                ('content_type', models.CharField(blank=True, default='', max_length=120)),
                ('size', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('evidencia', models.ForeignKey(db_column='evidencia_id', on_delete=django.db.models.deletion.CASCADE, related_name='archivos', to='planes.planevidencia')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='planes_evidencia_archivos_subidos', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Archivo evidencia plan',
                'verbose_name_plural': 'Archivos evidencia plan',
                'db_table': 'planes_evidencia_archivos',
                'ordering': ['created_at', 'id'],
            },
        ),
        migrations.CreateModel(
            name='PlanInstitucional',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anio', models.IntegerField(db_index=True)),
                ('nombre', models.CharField(max_length=512)),
                ('objetivo', models.TextField(blank=True, default='')),
                ('responsable_secretaria_nombre', models.CharField(blank=True, default='', max_length=256)),
                ('fecha_publicacion', models.DateField(blank=True, null=True)),
                ('url_publicacion', models.CharField(blank=True, default='', max_length=1024)),
                ('estado', models.CharField(choices=[('BORRADOR', 'Borrador'), ('PUBLICADO', 'Publicado'), ('EN_EJECUCION', 'En ejecución'), ('CERRADO', 'Cerrado')], default='BORRADOR', max_length=32)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('catalogo', models.ForeignKey(db_column='catalogo_id', on_delete=django.db.models.deletion.PROTECT, related_name='planes', to='planes.plancatalogo')),
                ('created_by', models.ForeignKey(blank=True, db_column='created_by_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='planes_creados', to=settings.AUTH_USER_MODEL)),
                ('entity', models.ForeignKey(db_column='entity_id', on_delete=django.db.models.deletion.CASCADE, related_name='planes_institucionales', to='entities.entity')),
                ('responsable_secretaria', models.ForeignKey(blank=True, db_column='responsable_secretaria_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='planes_responsable', to='entities.secretaria')),
                ('responsable_usuario', models.ForeignKey(blank=True, db_column='responsable_usuario_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='planes_responsable_usuario', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Plan institucional',
                'verbose_name_plural': 'Planes institucionales',
                'db_table': 'planes_institucionales',
                'ordering': ['anio', 'catalogo__orden', 'nombre'],
            },
        ),
        migrations.AddField(
            model_name='planactividad',
            name='plan',
            field=models.ForeignKey(db_column='plan_id', on_delete=django.db.models.deletion.CASCADE, related_name='actividades', to='planes.planinstitucional'),
        ),
        migrations.AddConstraint(
            model_name='plancatalogo',
            constraint=models.UniqueConstraint(fields=('entity', 'codigo'), name='uq_planes_catalogo_entity_codigo'),
        ),
        migrations.AddConstraint(
            model_name='plancatalogo',
            constraint=models.UniqueConstraint(condition=models.Q(('entity__isnull', True)), fields=('codigo',), name='uq_planes_catalogo_global_codigo'),
        ),
        migrations.AddIndex(
            model_name='planevidencia',
            index=models.Index(fields=['entity', 'actividad'], name='plan_evid_entity_act_idx'),
        ),
        migrations.AddIndex(
            model_name='planevidenciaarchivo',
            index=models.Index(fields=['evidencia'], name='plan_evarch_evid_idx'),
        ),
        migrations.AddIndex(
            model_name='planinstitucional',
            index=models.Index(fields=['entity', 'anio'], name='plan_entity_anio_idx'),
        ),
        migrations.AddIndex(
            model_name='planinstitucional',
            index=models.Index(fields=['entity', 'responsable_secretaria'], name='plan_entity_sec_idx'),
        ),
        migrations.AddConstraint(
            model_name='planinstitucional',
            constraint=models.UniqueConstraint(fields=('entity', 'catalogo', 'anio'), name='uq_plan_entity_catalogo_anio'),
        ),
        migrations.AddIndex(
            model_name='planactividad',
            index=models.Index(fields=['entity', 'plan'], name='plan_act_entity_plan_idx'),
        ),
        migrations.AddIndex(
            model_name='planactividad',
            index=models.Index(fields=['entity', 'anio', 'trimestre'], name='plan_act_entity_anio_tri_idx'),
        ),
        migrations.AddIndex(
            model_name='planactividad',
            index=models.Index(fields=['entity', 'responsable_secretaria'], name='plan_act_entity_sec_idx'),
        ),
    ]
