# Generated by Django 5.1.4 on 2026-08-04 19:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entities', '0006_entity_secop_nits'),
        ('planes', '0005_evidencias_multiples_cantidad_ejecutada'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InformePlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.CharField(blank=True, default='', max_length=255)),
                ('b2_key', models.CharField(blank=True, default='', max_length=500)),
                ('file_size', models.PositiveIntegerField(default=0)),
                ('tipo', models.CharField(choices=[('SEGUIMIENTO_D612', 'Informe de Seguimiento Decreto 612')], db_index=True, default='SEGUIMIENTO_D612', max_length=32)),
                ('anio', models.PositiveIntegerField()),
                ('trimestre', models.PositiveSmallIntegerField(choices=[(1, 'Trimestre I'), (2, 'Trimestre II'), (3, 'Trimestre III'), (4, 'Trimestre IV')])),
                ('incluir_evidencias', models.BooleanField(default=True)),
                ('usar_ia', models.BooleanField(default=False)),
                ('cargo_firmante', models.CharField(blank=True, default='', max_length=512)),
                ('estado', models.CharField(choices=[('PENDIENTE', 'En cola'), ('PROCESANDO', 'Generando'), ('COMPLETADO', 'Completado'), ('ERROR', 'Error')], db_index=True, default='PENDIENTE', max_length=16)),
                ('error_detail', models.TextField(blank=True, default='')),
                ('total_planes', models.PositiveIntegerField(default=0)),
                ('total_actividades', models.PositiveIntegerField(default=0)),
                ('avance_promedio', models.DecimalField(decimal_places=1, default=0, max_digits=5)),
                ('celery_task_id', models.CharField(blank=True, default='', max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('expires_at', models.DateTimeField(db_index=True)),
                ('created_by', models.ForeignKey(blank=True, db_column='created_by_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='informes_planes_creados', to=settings.AUTH_USER_MODEL)),
                ('entity', models.ForeignKey(db_column='entity_id', on_delete=django.db.models.deletion.CASCADE, related_name='informes_planes', to='entities.entity')),
                ('plan', models.ForeignKey(blank=True, db_column='plan_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='informes', to='planes.planinstitucional')),
                ('responsable_secretaria', models.ForeignKey(blank=True, db_column='responsable_secretaria_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='informes_planes', to='entities.secretaria')),
                ('usuario_firmante', models.ForeignKey(blank=True, db_column='usuario_firmante_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='informes_planes_firmados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Informe Planes Institucionales',
                'verbose_name_plural': 'Informes Planes Institucionales',
                'db_table': 'planes_informes',
                'ordering': ['-created_at', '-id'],
                'indexes': [models.Index(fields=['entity', '-created_at'], name='planes_info_entity__3d6545_idx'), models.Index(fields=['entity', 'estado'], name='planes_info_entity__c64ed6_idx'), models.Index(fields=['entity', 'expires_at'], name='planes_info_entity__1b4cda_idx'), models.Index(fields=['entity', 'tipo', 'estado'], name='planes_info_entity__25b200_idx')],
            },
        ),
    ]
