# Generated by Django 5.1.4 on 2026-06-01 19:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("entities", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name='PdmActividad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_producto', models.CharField(db_index=True, max_length=64)),
                ('anio', models.IntegerField(db_index=True)),
                ('nombre', models.CharField(max_length=512)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('fecha_inicio', models.DateTimeField(blank=True, null=True)),
                ('fecha_fin', models.DateTimeField(blank=True, null=True)),
                ('meta_ejecutar', models.FloatField(default=0)),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('EN_PROGRESO', 'En progreso'), ('COMPLETADA', 'Completada'), ('CANCELADA', 'Cancelada')], default='PENDIENTE', max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('entity', models.ForeignKey(db_column='entity_id', on_delete=django.db.models.deletion.CASCADE, related_name='pdm_actividades', to='entities.entity')),
                ('responsable_secretaria', models.ForeignKey(blank=True, db_column='responsable_secretaria_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pdm_actividades_responsable', to='entities.secretaria')),
            ],
            options={
                'verbose_name': 'Actividad PDM',
                'verbose_name_plural': 'Actividades PDM',
                'db_table': 'pdm_actividades',
                'ordering': ['anio', 'id'],
            },
        ),
        migrations.CreateModel(
            name='PdmActividadEvidencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.TextField()),
                ('url_evidencia', models.CharField(blank=True, max_length=1024, null=True)),
                ('imagenes', models.JSONField(blank=True, null=True)),
                ('imagenes_s3_urls', models.JSONField(blank=True, null=True)),
                ('migrated_to_s3', models.BooleanField(default=False)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('actividad', models.OneToOneField(db_column='actividad_id', on_delete=django.db.models.deletion.CASCADE, related_name='evidencia', to='pdm.pdmactividad')),
                ('entity', models.ForeignKey(db_column='entity_id', on_delete=django.db.models.deletion.CASCADE, related_name='pdm_evidencias', to='entities.entity')),
            ],
            options={
                'verbose_name': 'Evidencia PDM',
                'verbose_name_plural': 'Evidencias PDM',
                'db_table': 'pdm_actividades_evidencias',
            },
        ),
        migrations.CreateModel(
            name='PDMContratoRPS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_producto', models.TextField(db_index=True)),
                ('no_crp', models.CharField(max_length=100)),
                ('concepto', models.TextField(blank=True, null=True)),
                ('valor', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('anio', models.IntegerField(db_index=True)),
                ('contratista', models.CharField(blank=True, max_length=500, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('entity', models.ForeignKey(db_column='entity_id', on_delete=django.db.models.deletion.CASCADE, related_name='pdm_contratos_rps', to='entities.entity')),
            ],
            options={
                'verbose_name': 'Contrato RPS PDM',
                'verbose_name_plural': 'Contratos RPS PDM',
                'db_table': 'pdm_contratos_rps',
            },
        ),
        migrations.CreateModel(
            name='PDMEjecucionPresupuestal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_producto', models.CharField(db_index=True, max_length=20)),
                ('descripcion_fte', models.CharField(max_length=500)),
                ('pto_inicial', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('adicion', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('reduccion', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('credito', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('contracredito', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('pto_definitivo', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('pagos', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('sector', models.CharField(blank=True, max_length=100, null=True)),
                ('dependencia', models.CharField(blank=True, max_length=200, null=True)),
                ('bpin', models.CharField(blank=True, max_length=50, null=True)),
                ('anio', models.IntegerField(blank=True, db_index=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('entity', models.ForeignKey(db_column='entity_id', on_delete=django.db.models.deletion.CASCADE, related_name='pdm_ejecuciones', to='entities.entity')),
            ],
            options={
                'verbose_name': 'Ejecución presupuestal PDM',
                'verbose_name_plural': 'Ejecuciones presupuestales PDM',
                'db_table': 'pdm_ejecucion_presupuestal',
            },
        ),
        migrations.CreateModel(
            name='PdmIniciativaSGR',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_dane', models.CharField(blank=True, max_length=20, null=True)),
                ('entidad_territorial', models.CharField(blank=True, max_length=256, null=True)),
                ('nombre_plan', models.CharField(blank=True, max_length=512, null=True)),
                ('consecutivo', models.CharField(db_index=True, max_length=128)),
                ('linea_estrategica', models.TextField(blank=True, null=True)),
                ('tipo_iniciativa', models.CharField(blank=True, max_length=256, null=True)),
                ('sector_mga', models.CharField(blank=True, max_length=256, null=True)),
                ('iniciativa_sgr', models.TextField(blank=True, null=True)),
                ('recursos_sgr_indicativos', models.FloatField(default=0)),
                ('bpin', models.CharField(blank=True, max_length=50, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('entity', models.ForeignKey(db_column='entity_id', on_delete=django.db.models.deletion.CASCADE, related_name='pdm_iniciativas_sgr', to='entities.entity')),
            ],
            options={
                'verbose_name': 'Iniciativa SGR',
                'verbose_name_plural': 'Iniciativas SGR',
                'db_table': 'pdm_iniciativas_sgr',
            },
        ),
        migrations.CreateModel(
            name='PdmProducto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_dane', models.CharField(blank=True, max_length=20, null=True)),
                ('entidad_territorial', models.CharField(blank=True, max_length=256, null=True)),
                ('nombre_plan', models.CharField(blank=True, max_length=512, null=True)),
                ('codigo_indicador_producto', models.TextField(blank=True, null=True)),
                ('codigo_producto', models.CharField(db_index=True, max_length=64)),
                ('linea_estrategica', models.TextField(blank=True, null=True)),
                ('codigo_sector', models.TextField(blank=True, null=True)),
                ('sector_mga', models.TextField(blank=True, null=True)),
                ('codigo_programa', models.TextField(blank=True, null=True)),
                ('programa_mga', models.TextField(blank=True, null=True)),
                ('codigo_producto_mga', models.TextField(blank=True, null=True)),
                ('producto_mga', models.TextField(blank=True, null=True)),
                ('codigo_indicador_producto_mga', models.TextField(blank=True, null=True)),
                ('indicador_producto_mga', models.TextField(blank=True, null=True)),
                ('personalizacion_indicador', models.TextField(blank=True, null=True)),
                ('unidad_medida', models.TextField(blank=True, null=True)),
                ('meta_cuatrienio', models.FloatField(blank=True, null=True)),
                ('principal', models.CharField(blank=True, max_length=10, null=True)),
                ('codigo_ods', models.CharField(blank=True, max_length=50, null=True)),
                ('ods', models.TextField(blank=True, null=True)),
                ('tipo_acumulacion', models.TextField(blank=True, null=True)),
                ('bpin', models.CharField(blank=True, max_length=50, null=True)),
                ('responsable_secretaria_nombre', models.CharField(blank=True, max_length=256, null=True)),
                ('programacion_2024', models.FloatField(default=0)),
                ('programacion_2025', models.FloatField(default=0)),
                ('programacion_2026', models.FloatField(default=0)),
                ('programacion_2027', models.FloatField(default=0)),
                ('presupuesto_2024', models.JSONField(blank=True, null=True)),
                ('presupuesto_2025', models.JSONField(blank=True, null=True)),
                ('presupuesto_2026', models.JSONField(blank=True, null=True)),
                ('presupuesto_2027', models.JSONField(blank=True, null=True)),
                ('total_2024', models.FloatField(default=0)),
                ('total_2025', models.FloatField(default=0)),
                ('total_2026', models.FloatField(default=0)),
                ('total_2027', models.FloatField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('entity', models.ForeignKey(db_column='entity_id', on_delete=django.db.models.deletion.CASCADE, related_name='pdm_productos', to='entities.entity')),
                ('responsable_secretaria', models.ForeignKey(blank=True, db_column='responsable_secretaria_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pdm_productos_responsable', to='entities.secretaria')),
            ],
            options={
                'verbose_name': 'Producto PDM',
                'verbose_name_plural': 'Productos PDM',
                'db_table': 'pdm_productos',
                'ordering': ['codigo_producto'],
            },
        ),
        migrations.AddIndex(
            model_name='pdmactividad',
            index=models.Index(fields=['entity', 'codigo_producto'], name='pdm_act_entity_prod_idx'),
        ),
        migrations.AddIndex(
            model_name='pdmactividad',
            index=models.Index(fields=['entity', 'anio'], name='pdm_act_entity_anio_idx'),
        ),
        migrations.AddIndex(
            model_name='pdmactividad',
            index=models.Index(fields=['entity', 'responsable_secretaria'], name='pdm_act_entity_sec_idx'),
        ),
        migrations.AddIndex(
            model_name='pdmactividadevidencia',
            index=models.Index(fields=['entity', 'actividad'], name='pdm_evid_entity_act_idx'),
        ),
        migrations.AddIndex(
            model_name='pdmcontratorps',
            index=models.Index(fields=['entity', 'codigo_producto', 'anio'], name='pdm_ctr_entity_prod_anio_idx'),
        ),
        migrations.AddIndex(
            model_name='pdmcontratorps',
            index=models.Index(fields=['entity', 'anio'], name='pdm_ctr_entity_anio_idx'),
        ),
        migrations.AddIndex(
            model_name='pdmejecucionpresupuestal',
            index=models.Index(fields=['entity', 'codigo_producto', 'anio'], name='pdm_ejec_entity_prod_anio_idx'),
        ),
        migrations.AddIndex(
            model_name='pdmejecucionpresupuestal',
            index=models.Index(fields=['entity', 'anio'], name='pdm_ejec_entity_anio_idx'),
        ),
        migrations.AddConstraint(
            model_name='pdmejecucionpresupuestal',
            constraint=models.UniqueConstraint(fields=('entity', 'codigo_producto', 'descripcion_fte', 'anio'), name='uq_pdm_ejec_entity_prod_fte_anio'),
        ),
        migrations.AddIndex(
            model_name='pdminiciativasgr',
            index=models.Index(fields=['entity', 'consecutivo'], name='pdm_inic_entity_consec_idx'),
        ),
        migrations.AddConstraint(
            model_name='pdminiciativasgr',
            constraint=models.UniqueConstraint(fields=('entity', 'consecutivo'), name='uq_pdm_inic_sgr_entity_consec'),
        ),
        migrations.AddIndex(
            model_name='pdmproducto',
            index=models.Index(fields=['entity', 'codigo_producto'], name='pdm_prod_entity_codigo_idx'),
        ),
        migrations.AddIndex(
            model_name='pdmproducto',
            index=models.Index(fields=['entity', 'responsable_secretaria'], name='pdm_prod_entity_sec_idx'),
        ),
        migrations.AddConstraint(
            model_name='pdmproducto',
            constraint=models.UniqueConstraint(fields=('entity', 'codigo_producto'), name='uq_pdm_producto_entity_codigo'),
        ),
    ]
