# Generated by Django 5.1.4 on 2026-07-28 16:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pdm', '0005_b2_storage'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='pdmactividad',
            name='responsable_usuario',
            field=models.ForeignKey(blank=True, db_column='responsable_usuario_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pdm_actividades_responsable_usuario', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='pdmproducto',
            name='responsable_usuario',
            field=models.ForeignKey(blank=True, db_column='responsable_usuario_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pdm_productos_responsable_usuario', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='pdmchatconversation',
            name='session_uuid',
            field=models.UUIDField(db_index=True),
        ),
    ]
