# Generated by Django 5.1.4 on 2026-08-04 02:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entities', '0006_entity_secop_nits'),
        ('pdm', '0006_multi_entity_delegation'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InformePDM',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.CharField(blank=True, default='', max_length=255)),
                ('b2_key', models.CharField(blank=True, default='', max_length=500)),
                ('file_size', models.PositiveIntegerField(default=0)),
                ('anio', models.PositiveIntegerField()),
                ('incluir_evidencias', models.BooleanField(default=True)),
                ('usar_ia', models.BooleanField(default=False)),
                ('estado', models.CharField(choices=[('PENDIENTE', 'En cola'), ('PROCESANDO', 'Generando'), ('COMPLETADO', 'Completado'), ('ERROR', 'Error')], db_index=True, default='PENDIENTE', max_length=16)),
                ('error_detail', models.TextField(blank=True, default='')),
                ('total_productos', models.PositiveIntegerField(default=0)),
                ('avance_fisico', models.DecimalField(decimal_places=1, default=0, max_digits=5)),
                ('avance_financiero', models.DecimalField(decimal_places=1, default=0, max_digits=5)),
                ('celery_task_id', models.CharField(blank=True, default='', max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('expires_at', models.DateTimeField(db_index=True)),
                ('created_by', models.ForeignKey(blank=True, db_column='created_by_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='informes_pdm_creados', to=settings.AUTH_USER_MODEL)),
                ('entity', models.ForeignKey(db_column='entity_id', on_delete=django.db.models.deletion.CASCADE, related_name='informes_pdm', to='entities.entity')),
                ('responsable_secretaria', models.ForeignKey(blank=True, db_column='responsable_secretaria_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='informes_pdm', to='entities.secretaria')),
                ('usuario_firmante', models.ForeignKey(blank=True, db_column='usuario_firmante_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='informes_pdm_firmados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Informe PDM',
                'verbose_name_plural': 'Informes PDM',
                'db_table': 'pdm_informes',
                'ordering': ['-created_at', '-id'],
                'indexes': [models.Index(fields=['entity', '-created_at'], name='pdm_informe_entity__28ed70_idx'), models.Index(fields=['entity', 'estado'], name='pdm_informe_entity__ad3fd2_idx'), models.Index(fields=['entity', 'expires_at'], name='pdm_informe_entity__ed3d88_idx')],
            },
        ),
    ]
