# Generated by Django 5.1.4 on 2026-08-04 03:03

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entities', '0006_entity_secop_nits'),
        ('pdm', '0007_informe_pdm'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='informepdm',
            name='tipo',
            field=models.CharField(choices=[('AVANCE', 'Informe de Avance de PDM'), ('GESTION', 'Informe de Gestión')], db_index=True, default='AVANCE', max_length=16),
        ),
        migrations.AddIndex(
            model_name='informepdm',
            index=models.Index(fields=['entity', 'tipo', 'estado'], name='pdm_informe_entity__6b177d_idx'),
        ),
    ]
