import type { LucideIcon } from "lucide-react";
import {
  Archive,
  ArrowLeft,
  ArrowRight,
  BarChart3,
  Barcode,
  Bell,
  Bot,
  Boxes,
  Brain,
  Building2,
  Calendar,
  Camera,
  CheckCircle,
  CheckSquare,
  ChevronRight,
  Clock,
  Cloud,
  CloudUpload,
  Code,
  Code2,
  Compass,
  Container,
  Database,
  DollarSign,
  Eye,
  Factory,
  FileCode,
  FileSpreadsheet,
  FileText,
  Flag,
  Gauge,
  Handshake,
  Heart,
  History,
  Home,
  Inbox,
  Landmark,
  Layers,
  Lightbulb,
  ListTodo,
  LogIn,
  Mail,
  MapPin,
  MapPinned,
  MemoryStick,
  MessageSquare,
  Network,
  Package,
  Palette,
  Phone,
  PieChart,
  RefreshCw,
  Rocket,
  Scale,
  Server,
  Shield,
  ShieldCheck,
  Network as SitemapIcon,
  Sparkles,
  Sprout,
  Star,
  UserCheck,
  UserCog,
  Users,
  X,
  Zap,
} from "lucide-react";

const ICON_MAP: Record<string, LucideIcon> = {
  "fas fa-star": Star,
  "fas fa-map-marked-alt": MapPinned,
  "fas fa-brain": Brain,
  "fas fa-file-pdf": FileText,
  "fas fa-shield-alt": Shield,
  "fas fa-users": Users,
  "fas fa-cubes": Boxes,
  "fas fa-sync-alt": RefreshCw,
  "fas fa-building": Building2,
  "fas fa-chart-line": BarChart3,
  "fas fa-cloud-upload-alt": CloudUpload,
  "fas fa-envelope-open-text": Mail,
  "fas fa-database": Database,
  "fas fa-users-cog": UserCog,
  "fas fa-comments": MessageSquare,
  "fas fa-sitemap": SitemapIcon,
  "fas fa-file-excel": FileSpreadsheet,
  "fas fa-camera": Camera,
  "fas fa-flag": Flag,
  "fas fa-industry": Factory,
  "fas fa-box": Package,
  "fas fa-tasks": ListTodo,
  "fas fa-dollar-sign": DollarSign,
  "fas fa-check-circle": CheckCircle,
  "fas fa-check-square": CheckSquare,
  "fas fa-chevron-right": ChevronRight,
  "fas fa-layer-group": Layers,
  "fas fa-calendar-alt": Calendar,
  "fas fa-robot": Bot,
  "fas fa-cloud": Cloud,
  "fas fa-rocket": Rocket,
  "fas fa-chart-bar": BarChart3,
  "fas fa-bolt": Zap,
  "fas fa-city": Building2,
  "fas fa-landmark": Landmark,
  "fas fa-hospital": Building2,
  "fab fa-react": Sparkles,
  "fab fa-js": FileCode,
  "fab fa-python": Code2,
  "fab fa-docker": Container,
  "fas fa-code": Code,
  "fas fa-palette": Palette,
  "fas fa-user-shield": ShieldCheck,
  "fas fa-chart-pie": PieChart,
  "fas fa-memory": MemoryStick,
  "fas fa-inbox": Inbox,
  "fas fa-bell": Bell,
  "fas fa-file-contract": FileText,
  "fas fa-handshake": Handshake,
  "fas fa-tachometer-alt": Gauge,
  "fas fa-mail-bulk": Archive,
  "fas fa-barcode": Barcode,
  "fas fa-clock": Clock,
  "fas fa-history": History,
  "fas fa-user-clock": Clock,
  "fas fa-user-check": UserCheck,
  "fas fa-lightbulb": Lightbulb,
  "fas fa-network-wired": Network,
  "fas fa-user-tie": UserCog,
  "fas fa-eye": Eye,
  "fas fa-balance-scale": Scale,
  "fas fa-seedling": Sprout,
  "fas fa-envelope": Mail,
  "fas fa-phone": Phone,
  "fas fa-map-marker-alt": MapPin,
  "fab fa-whatsapp": MessageSquare,
  "fas fa-sign-in-alt": LogIn,
  "fas fa-times": X,
  "fas fa-arrow-left": ArrowLeft,
  "fas fa-arrow-right": ArrowRight,
  "fas fa-home": Home,
  "fas fa-compass": Compass,
  "fas fa-heart": Heart,
  "fas fa-server": Server,
};

interface Props {
  icon: string;
  size?: number;
  className?: string;
  strokeWidth?: number;
}

export default function ShowcaseIcon({ icon, size = 20, className, strokeWidth = 2 }: Props) {
  const Icon = ICON_MAP[icon] ?? Sparkles;
  return <Icon size={size} className={className} strokeWidth={strokeWidth} aria-hidden />;
}
