# Generated by Django 5.1.4 on 2026-07-28 16:43

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pqrs', '0015_informepqrs'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='asignacionauditoria',
            new_name='asignacion__pqrs_id_3904e2_idx',
            old_name='asig_audit_pqrs_idx',
        ),
        migrations.RenameIndex(
            model_name='asignacionauditoria',
            new_name='asignacion__fecha_a_d8fedf_idx',
            old_name='asig_audit_fecha_idx',
        ),
        migrations.RenameIndex(
            model_name='correoentrantepqrs',
            new_name='pqrs_correo_remiten_bc86c9_idx',
            old_name='pqrs_ce_rem_fecha_idx',
        ),
        migrations.RenameIndex(
            model_name='correoentrantepqrs',
            new_name='pqrs_correo_estado_d11756_idx',
            old_name='pqrs_ce_est_fecha_idx',
        ),
        migrations.RenameIndex(
            model_name='informepqrs',
            new_name='pqrs_inform_entity__aca10b_idx',
            old_name='pqrs_inf_entity_created_idx',
        ),
        migrations.RenameIndex(
            model_name='informepqrs',
            new_name='pqrs_inform_entity__08df17_idx',
            old_name='pqrs_inf_entity_exp_idx',
        ),
        migrations.RenameIndex(
            model_name='pqrs',
            new_name='pqrs_estado_564554_idx',
            old_name='pqrs_estado_idx',
        ),
        migrations.RenameIndex(
            model_name='pqrs',
            new_name='pqrs_tipo_so_2a9a6e_idx',
            old_name='pqrs_tipo_sol_idx',
        ),
        migrations.RenameIndex(
            model_name='pqrs',
            new_name='pqrs_canal_l_eec35a_idx',
            old_name='pqrs_canal_idx',
        ),
        migrations.RenameIndex(
            model_name='pqrsarchivo',
            new_name='pqrs_archiv_pqrs_id_b62b50_idx',
            old_name='pqrs_archiv_pqrs_id_idx',
        ),
        migrations.RenameIndex(
            model_name='pqrscorreo',
            new_name='pqrs_correo_pqrs_id_a19632_idx',
            old_name='pqrs_correo_pqrs_created_idx',
        ),
        migrations.RenameIndex(
            model_name='pqrscorreo',
            new_name='pqrs_correo_request_e1ce91_idx',
            old_name='pqrs_correo_request_id_idx',
        ),
        migrations.AddField(
            model_name='pqrs',
            name='assigned_users',
            field=models.ManyToManyField(blank=True, db_table='pqrs_usuarios_asignados', help_text='Usuarios delegados (p. ej. contratistas bajo un secretario).', related_name='pqrs_asignadas_usuario', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='asignacionauditoria',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='pqrs',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='pqrscorreo',
            name='estado',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('enviado', 'Enviado'), ('entregado', 'Entregado'), ('rebote_temporal', 'Rebote temporal'), ('rebotado', 'Rebotado'), ('reclamacion_spam', 'Marcado como spam'), ('error', 'Error')], default='pendiente', max_length=20),
        ),
        migrations.AlterField(
            model_name='pqrscorreo',
            name='tipo',
            field=models.CharField(choices=[('radicacion', 'Radicación'), ('respuesta', 'Respuesta'), ('asignacion', 'Asignación')], max_length=20),
        ),
    ]
