from django.urls import path

from .bpin_view import BpinDetailView
from .informes.views import InformePdmViewSet
from .views import (
    PdmActividadCreateView,
    PdmActividadDetailView,
    PdmActividadesPorProductoView,
    PdmArmonizacionCandidatosView,
    PdmArmonizacionDetailView,
    PdmArmonizacionListCreateView,
    PdmAnalisisView,
    PdmChatAnalyticsView,
    PdmProyectosView,
    PdmAsignarResponsableView,
    PdmAsignarResponsableUsuarioView,
    PdmContratosUploadView,
    PdmContratosView,
    PdmEjecucionProductoView,
    PdmEjecucionResumenAnualEntidadView,
    PdmEjecucionUploadView,
    PdmEjecucionMensualDeleteView,
    PdmEjecucionMensualListView,
    PdmEjecucionMensualUploadView,
    PdmExportPiipView,
    PdmExportPlanAccionView,
    PdmEvidenciaView,
    PdmMetaView,
    PdmProductoDetailView,
    PdmProductosListView,
    PdmStatsView,
    PdmStatusView,
    PdmUploadView,
)

urlpatterns = [
    path("pdm/v2/<slug:slug>/status", PdmStatusView.as_view()),
    path("pdm/v2/<slug:slug>/upload", PdmUploadView.as_view()),
    path("pdm/v2/<slug:slug>/meta", PdmMetaView.as_view()),
    path("pdm/v2/<slug:slug>/stats", PdmStatsView.as_view()),
    path("pdm/v2/<slug:slug>/analisis", PdmAnalisisView.as_view()),
    path("pdm/v2/<slug:slug>/proyectos", PdmProyectosView.as_view()),
    path("pdm/v2/<slug:slug>/export-piip", PdmExportPiipView.as_view()),
    path("pdm/v2/<slug:slug>/export-plan-accion", PdmExportPlanAccionView.as_view()),
    path("pdm/v2/<slug:slug>/chat/analytics/", PdmChatAnalyticsView.as_view()),
    path("pdm/v2/<slug:slug>/productos", PdmProductosListView.as_view()),
    path("pdm/v2/<slug:slug>/productos/<str:clave_producto>", PdmProductoDetailView.as_view()),
    path("pdm/v2/<slug:slug>/productos/<str:clave_producto>/actividades", PdmActividadesPorProductoView.as_view()),
    path("pdm/v2/<slug:slug>/actividades", PdmActividadCreateView.as_view()),
    path("pdm/v2/<slug:slug>/actividades/<int:actividad_id>", PdmActividadDetailView.as_view()),
    path("pdm/v2/<slug:slug>/actividades/<int:actividad_id>/evidencia", PdmEvidenciaView.as_view()),
    path("pdm/v2/<slug:slug>/productos/<str:clave_producto>/responsable", PdmAsignarResponsableView.as_view()),
    path(
        "pdm/v2/<slug:slug>/productos/<str:clave_producto>/responsable-usuario",
        PdmAsignarResponsableUsuarioView.as_view(),
    ),
    path("pdm/ejecucion/upload", PdmEjecucionUploadView.as_view()),
    path("pdm/ejecucion/mensual/", PdmEjecucionMensualListView.as_view()),
    path("pdm/ejecucion/mensual/upload", PdmEjecucionMensualUploadView.as_view()),
    path("pdm/ejecucion/mensual/<int:anio>/<int:mes>/", PdmEjecucionMensualDeleteView.as_view()),
    path("pdm/ejecucion/resumen-anual-entidad", PdmEjecucionResumenAnualEntidadView.as_view()),
    path("pdm/ejecucion/armonizaciones/candidatos/", PdmArmonizacionCandidatosView.as_view()),
    path("pdm/ejecucion/armonizaciones/", PdmArmonizacionListCreateView.as_view()),
    path("pdm/ejecucion/armonizaciones/<int:armonizacion_id>/", PdmArmonizacionDetailView.as_view()),
    path("pdm/ejecucion/<str:codigo_producto>", PdmEjecucionProductoView.as_view()),
    path("bpin/<str:bpin>", BpinDetailView.as_view()),
    path("pdm/contratos/<slug:slug>/upload", PdmContratosUploadView.as_view()),
    path("pdm/contratos/<slug:slug>/contratos", PdmContratosView.as_view()),
    path(
        "pdm/v2/<slug:slug>/informes/firmantes/",
        InformePdmViewSet.as_view({"get": "firmantes"}),
    ),
    path(
        "pdm/v2/<slug:slug>/informes/",
        InformePdmViewSet.as_view({"get": "list", "post": "create"}),
    ),
    path(
        "pdm/v2/<slug:slug>/informes/<int:pk>/",
        InformePdmViewSet.as_view({"delete": "destroy"}),
    ),
    path(
        "pdm/v2/<slug:slug>/informes/<int:pk>/download/",
        InformePdmViewSet.as_view({"get": "download"}),
    ),
]
