# Generated by Django 5.1.4 on 2026-08-30 15:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('entities', '0007_initial_gestion_documental'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InstrumentoArchivistico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('ccd', 'Cuadro de Clasificación Documental (CCD)'), ('trd', 'Tabla de Retención Documental (TRD)'), ('tvd', 'Tabla de Valoración Documental (TVD)'), ('pgd', 'Programa de Gestión Documental (PGD)'), ('pinar', 'Plan Institucional de Archivos (PINAR)'), ('fuid', 'Formato Único de Inventario Documental (FUID)'), ('sic', 'Sistema Integrado de Conservación (SIC)'), ('banco_terminologico', 'Banco terminológico'), ('modelo_requisitos', 'Modelo de requisitos documentos electrónicos'), ('diagnostico', 'Diagnóstico integral de gestión documental')], max_length=40)),
                ('vigencia', models.PositiveSmallIntegerField()),
                ('version', models.CharField(blank=True, default='1.0', max_length=50)),
                ('estado', models.CharField(choices=[('borrador', 'Borrador'), ('aprobado_comite', 'Aprobado Comité Interno de Archivo'), ('presentado_consejo', 'Presentado al Consejo Territorial'), ('convalidado', 'Convalidado'), ('inscrito_rusd', 'Inscrito en RUSD'), ('vigente', 'Vigente')], default='borrador', max_length=30)),
                ('titulo', models.CharField(blank=True, default='', max_length=300)),
                ('acta_comite', models.CharField(blank=True, default='', max_length=100)),
                ('fecha_aprobacion_comite', models.DateField(blank=True, null=True)),
                ('fecha_convalidacion', models.DateField(blank=True, null=True)),
                ('codigo_rusd', models.CharField(blank=True, default='', max_length=100)),
                ('b2_key', models.CharField(blank=True, default='', max_length=500)),
                ('nombre_archivo', models.CharField(blank=True, default='', max_length=255)),
                ('content_type', models.CharField(blank=True, default='', max_length=120)),
                ('size', models.PositiveIntegerField(default=0)),
                ('notas', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='instrumentos_gd_creados', to=settings.AUTH_USER_MODEL)),
                ('entity', models.ForeignKey(db_column='entity_id', on_delete=django.db.models.deletion.CASCADE, related_name='instrumentos_archivisticos', to='entities.entity')),
            ],
            options={
                'db_table': 'gd_instrumentos',
                'ordering': ['-vigencia', '-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='SerieDocumental',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=50)),
                ('nombre', models.CharField(max_length=300)),
                ('es_subserie', models.BooleanField(default=False)),
                ('tipos_documentales', models.JSONField(blank=True, default=list)),
                ('retencion_gestion_anios', models.PositiveSmallIntegerField(default=0)),
                ('retencion_central_anios', models.PositiveSmallIntegerField(default=0)),
                ('disposicion_final', models.CharField(choices=[('CT', 'Conservación total'), ('S', 'Selección'), ('E', 'Eliminación'), ('MD', 'Microfilmación / digitalización')], default='CT', max_length=5)),
                ('procedimiento', models.TextField(blank=True, default='')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('entity', models.ForeignKey(db_column='entity_id', on_delete=django.db.models.deletion.CASCADE, related_name='series_documentales', to='entities.entity')),
                ('instrumento', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='series', to='gestion_documental.instrumentoarchivistico')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subseries', to='gestion_documental.seriedocumental')),
            ],
            options={
                'db_table': 'gd_series_documentales',
                'ordering': ['codigo'],
            },
        ),
        migrations.CreateModel(
            name='Expediente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=60)),
                ('titulo', models.CharField(max_length=400)),
                ('etapa', models.CharField(choices=[('gestion', 'Archivo de gestión'), ('central', 'Archivo central'), ('historico', 'Archivo histórico')], default='gestion', max_length=20)),
                ('estado', models.CharField(choices=[('abierto', 'Abierto'), ('cerrado', 'Cerrado')], default='abierto', max_length=20)),
                ('soporte', models.CharField(choices=[('fisico', 'Físico'), ('electronico', 'Electrónico'), ('hibrido', 'Híbrido')], default='electronico', max_length=20)),
                ('fecha_extrema_inicial', models.DateField(blank=True, null=True)),
                ('fecha_extrema_final', models.DateField(blank=True, null=True)),
                ('folios', models.PositiveIntegerField(default=0)),
                ('notas', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='expedientes_gd_creados', to=settings.AUTH_USER_MODEL)),
                ('entity', models.ForeignKey(db_column='entity_id', on_delete=django.db.models.deletion.CASCADE, related_name='expedientes_gd', to='entities.entity')),
                ('responsable', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='expedientes_gd_responsable', to=settings.AUTH_USER_MODEL)),
                ('secretaria', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='expedientes_gd', to='entities.secretaria')),
                ('serie', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='expedientes', to='gestion_documental.seriedocumental')),
            ],
            options={
                'db_table': 'gd_expedientes',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='Transferencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('primaria', 'Transferencia primaria'), ('secundaria', 'Transferencia secundaria')], max_length=20)),
                ('estado', models.CharField(choices=[('borrador', 'Borrador'), ('ejecutada', 'Ejecutada')], default='borrador', max_length=20)),
                ('acta', models.CharField(blank=True, default='', max_length=100)),
                ('b2_key_acta', models.CharField(blank=True, default='', max_length=500)),
                ('notas', models.TextField(blank=True, default='')),
                ('ejecutada_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transferencias_gd_creadas', to=settings.AUTH_USER_MODEL)),
                ('entity', models.ForeignKey(db_column='entity_id', on_delete=django.db.models.deletion.CASCADE, related_name='transferencias_gd', to='entities.entity')),
                ('expedientes', models.ManyToManyField(related_name='transferencias', to='gestion_documental.expediente')),
            ],
            options={
                'db_table': 'gd_transferencias',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UnidadAdministrativa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=30)),
                ('nombre', models.CharField(max_length=250)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('entity', models.ForeignKey(db_column='entity_id', on_delete=django.db.models.deletion.CASCADE, related_name='unidades_administrativas_gd', to='entities.entity')),
                ('secretaria', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='unidades_administrativas_gd', to='entities.secretaria')),
            ],
            options={
                'db_table': 'gd_unidades_administrativas',
                'ordering': ['codigo'],
            },
        ),
        migrations.AddField(
            model_name='seriedocumental',
            name='unidad',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='series', to='gestion_documental.unidadadministrativa'),
        ),
        migrations.AddField(
            model_name='expediente',
            name='unidad',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='expedientes', to='gestion_documental.unidadadministrativa'),
        ),
        migrations.CreateModel(
            name='EventoGD',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('creacion', 'Creación'), ('cambio_estado', 'Cambio de estado'), ('documento', 'Documento'), ('transferencia', 'Transferencia'), ('disposicion', 'Disposición'), ('instrumento', 'Instrumento archivístico'), ('otro', 'Otro')], max_length=30)),
                ('detalle', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='eventos_gd', to=settings.AUTH_USER_MODEL)),
                ('entity', models.ForeignKey(db_column='entity_id', on_delete=django.db.models.deletion.CASCADE, related_name='eventos_gd', to='entities.entity')),
            ],
            options={
                'db_table': 'gd_eventos',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['entity', 'tipo', 'created_at'], name='gd_eventos_entity__165475_idx')],
            },
        ),
        migrations.CreateModel(
            name='DocumentoExpediente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('tipo_documental', models.CharField(blank=True, default='', max_length=150)),
                ('b2_key', models.CharField(blank=True, default='', max_length=500)),
                ('content_type', models.CharField(blank=True, default='', max_length=120)),
                ('size', models.PositiveIntegerField(default=0)),
                ('sha256', models.CharField(blank=True, default='', max_length=64)),
                ('version', models.PositiveSmallIntegerField(default=1)),
                ('folio_inicio', models.PositiveIntegerField(blank=True, null=True)),
                ('folio_fin', models.PositiveIntegerField(blank=True, null=True)),
                ('fecha_documento', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('entity', models.ForeignKey(db_column='entity_id', on_delete=django.db.models.deletion.CASCADE, related_name='documentos_expediente_gd', to='entities.entity')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documentos_gd_subidos', to=settings.AUTH_USER_MODEL)),
                ('expediente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documentos', to='gestion_documental.expediente')),
            ],
            options={
                'db_table': 'gd_documentos_expediente',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['entity', 'expediente'], name='gd_document_entity__e7fac0_idx')],
            },
        ),
        migrations.CreateModel(
            name='Disposicion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('disposicion_final', models.CharField(choices=[('CT', 'Conservación total'), ('S', 'Selección'), ('E', 'Eliminación'), ('MD', 'Microfilmación / digitalización')], max_length=5)),
                ('acta', models.CharField(blank=True, default='', max_length=100)),
                ('b2_key_acta', models.CharField(blank=True, default='', max_length=500)),
                ('notas', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='disposiciones_gd_creadas', to=settings.AUTH_USER_MODEL)),
                ('entity', models.ForeignKey(db_column='entity_id', on_delete=django.db.models.deletion.CASCADE, related_name='disposiciones_gd', to='entities.entity')),
                ('expedientes', models.ManyToManyField(related_name='disposiciones', to='gestion_documental.expediente')),
            ],
            options={
                'db_table': 'gd_disposiciones',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['entity', 'disposicion_final'], name='gd_disposic_entity__71f23d_idx')],
            },
        ),
        migrations.CreateModel(
            name='FuidRegistro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(blank=True, default='', max_length=50)),
                ('serie_nombre', models.CharField(blank=True, default='', max_length=300)),
                ('subserie_nombre', models.CharField(blank=True, default='', max_length=300)),
                ('unidad_documental', models.CharField(max_length=400)),
                ('fecha_inicial', models.DateField(blank=True, null=True)),
                ('fecha_final', models.DateField(blank=True, null=True)),
                ('soporte_fisico', models.BooleanField(default=False)),
                ('soporte_electronico', models.BooleanField(default=True)),
                ('caja', models.CharField(blank=True, default='', max_length=50)),
                ('carpeta', models.CharField(blank=True, default='', max_length=50)),
                ('tomo', models.CharField(blank=True, default='', max_length=50)),
                ('folios', models.PositiveIntegerField(default=0)),
                ('ubicacion', models.CharField(blank=True, default='', max_length=300)),
                ('notas', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('entity', models.ForeignKey(db_column='entity_id', on_delete=django.db.models.deletion.CASCADE, related_name='fuid_registros', to='entities.entity')),
                ('expediente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fuid_registros', to='gestion_documental.expediente')),
            ],
            options={
                'db_table': 'gd_fuid_registros',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['entity', 'created_at'], name='gd_fuid_reg_entity__f45b95_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='instrumentoarchivistico',
            index=models.Index(fields=['entity', 'tipo', 'estado'], name='gd_instrume_entity__62e102_idx'),
        ),
        migrations.AddIndex(
            model_name='instrumentoarchivistico',
            index=models.Index(fields=['entity', 'vigencia'], name='gd_instrume_entity__a5dc2d_idx'),
        ),
        migrations.AddIndex(
            model_name='transferencia',
            index=models.Index(fields=['entity', 'tipo', 'estado'], name='gd_transfer_entity__ab9784_idx'),
        ),
        migrations.AddIndex(
            model_name='unidadadministrativa',
            index=models.Index(fields=['entity', 'is_active'], name='gd_unidades_entity__f38039_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='unidadadministrativa',
            unique_together={('entity', 'codigo')},
        ),
        migrations.AddIndex(
            model_name='seriedocumental',
            index=models.Index(fields=['entity', 'codigo'], name='gd_series_d_entity__a0b966_idx'),
        ),
        migrations.AddIndex(
            model_name='seriedocumental',
            index=models.Index(fields=['entity', 'is_active'], name='gd_series_d_entity__5c019b_idx'),
        ),
        migrations.AddIndex(
            model_name='expediente',
            index=models.Index(fields=['entity', 'etapa'], name='gd_expedien_entity__3cc87a_idx'),
        ),
        migrations.AddIndex(
            model_name='expediente',
            index=models.Index(fields=['entity', 'estado'], name='gd_expedien_entity__546a6d_idx'),
        ),
        migrations.AddIndex(
            model_name='expediente',
            index=models.Index(fields=['entity', 'secretaria'], name='gd_expedien_entity__ff05d7_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='expediente',
            unique_together={('entity', 'codigo')},
        ),
    ]
