from django.urls import path

from .views import (
    Secop1AnaliticaView,
    Secop1ListView,
    Secop2AnaliticaView,
    Secop2ListView,
    Secop2PanelView,
    SecopAIAnalisisView,
    SecopAICopilotView,
    SecopAIContratoView,
    SecopAlertasView,
    SecopConfigView,
    SecopDependenciasView,
    SecopDetalleView,
    SecopEjecucionView,
    SecopEntidadesDatosGovView,
    SecopExportView,
    SecopPagosView,
    SecopRefrescarView,
    SecopResumenView,
    SecopVencimientosView,
)

urlpatterns = [
    path("secop/config/", SecopConfigView.as_view(), name="secop-config"),
    path("secop/resumen/", SecopResumenView.as_view(), name="secop-resumen"),
    path("secop/secop2/", Secop2ListView.as_view(), name="secop2-list"),
    path("secop/secop2/panel/", Secop2PanelView.as_view(), name="secop2-panel"),
    path("secop/secop2/analitica/", Secop2AnaliticaView.as_view(), name="secop2-analitica"),
    path("secop/secop1/", Secop1ListView.as_view(), name="secop1-list"),
    path("secop/secop1/analitica/", Secop1AnaliticaView.as_view(), name="secop1-analitica"),
    path("secop/ejecucion/", SecopEjecucionView.as_view(), name="secop-ejecucion"),
    path("secop/dependencias/", SecopDependenciasView.as_view(), name="secop-dependencias"),
    path("secop/vencimientos/", SecopVencimientosView.as_view(), name="secop-vencimientos"),
    path("secop/pagos/", SecopPagosView.as_view(), name="secop-pagos"),
    path("secop/alertas/", SecopAlertasView.as_view(), name="secop-alertas"),
    path("secop/detalle/", SecopDetalleView.as_view(), name="secop-detalle"),
    path("secop/export/", SecopExportView.as_view(), name="secop-export"),
    path("secop/refrescar/", SecopRefrescarView.as_view(), name="secop-refrescar"),
    path("secop/entidades-datos-gov/", SecopEntidadesDatosGovView.as_view(), name="secop-entidades-datos-gov"),
    path("secop/ai/analisis/", SecopAIAnalisisView.as_view(), name="secop-ai-analisis"),
    path("secop/ai/copilot/", SecopAICopilotView.as_view(), name="secop-ai-copilot"),
    path("secop/ai/contrato/", SecopAIContratoView.as_view(), name="secop-ai-contrato"),
]
