# Generated by Django 5.1.4 on 2026-06-03 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_user_secretario_requires_secretaria'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='clerk_id',
            field=models.CharField(blank=True, db_index=True, help_text='ID del usuario en Clerk (user_xxx).', max_length=255, null=True, unique=True),
        ),
    ]
