# Generated by Django 5.1.4 on 2026-07-28 16:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_user_email_firma'),
        ('auth', '0012_alter_user_first_name_max_length'),
        ('entities', '0005_multi_entity_delegation'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserEntityMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(blank=True, choices=[('superadmin', 'Superadmin'), ('admin', 'Admin'), ('secretario', 'Secretario'), ('contratista', 'Contratista'), ('ciudadano', 'Ciudadano')], default='', max_length=20)),
                ('enabled_modules', models.JSONField(blank=True, default=list)),
                ('is_active', models.BooleanField(default=True)),
                ('is_default', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Membresía de entidad',
                'verbose_name_plural': 'Membresías de entidad',
                'ordering': ['entity__name', 'user__email'],
            },
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(blank=True, choices=[('superadmin', 'Superadmin'), ('admin', 'Admin'), ('secretario', 'Secretario'), ('contratista', 'Contratista'), ('ciudadano', 'Ciudadano')], default='', max_length=20),
        ),
        migrations.AddConstraint(
            model_name='user',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('role', 'contratista'), _negated=True), ('secretaria__isnull', False), _connector='OR'), name='user_contratista_requires_secretaria'),
        ),
        migrations.AddField(
            model_name='userentitymembership',
            name='entity',
            field=models.ForeignKey(db_column='entity_id', on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='entities.entity'),
        ),
        migrations.AddField(
            model_name='userentitymembership',
            name='secretaria',
            field=models.ForeignKey(blank=True, db_column='secretaria_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='memberships', to='entities.secretaria'),
        ),
        migrations.AddField(
            model_name='userentitymembership',
            name='supervisor',
            field=models.ForeignKey(blank=True, db_column='supervisor_id', help_text='Supervisor directo (p. ej. secretario del contratista).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='supervised_memberships', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='userentitymembership',
            name='user',
            field=models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddConstraint(
            model_name='userentitymembership',
            constraint=models.UniqueConstraint(fields=('user', 'entity'), name='unique_user_entity_membership'),
        ),
        migrations.AddConstraint(
            model_name='userentitymembership',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('role', 'secretario'), _negated=True), ('secretaria__isnull', False), _connector='OR'), name='membership_secretario_requires_secretaria'),
        ),
        migrations.AddConstraint(
            model_name='userentitymembership',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('role', 'contratista'), _negated=True), ('secretaria__isnull', False), _connector='OR'), name='membership_contratista_requires_secretaria'),
        ),
    ]
