# Generated by Django 5.1.4 on 2026-07-20 15:37

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('entities', '0004_entity_asistencias_por_dia'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Correspondencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_radicado', models.CharField(max_length=40)),
                ('sentido', models.CharField(choices=[('entrada', 'Entrada'), ('salida', 'Salida')], max_length=20)),
                ('tipologia', models.CharField(choices=[('oficio', 'Oficio'), ('memorando', 'Memorando'), ('circular', 'Circular'), ('derecho_peticion', 'Derecho de petición'), ('remision', 'Remisión'), ('otro', 'Otro')], default='oficio', max_length=40)),
                ('fecha_radicacion', models.DateTimeField(default=django.utils.timezone.now)),
                ('remitente_nombre', models.CharField(max_length=250)),
                ('remitente_documento', models.CharField(blank=True, default='', max_length=50)),
                ('remitente_dependencia', models.CharField(blank=True, default='', max_length=250)),
                ('destinatario_nombre', models.CharField(max_length=250)),
                ('destinatario_documento', models.CharField(blank=True, default='', max_length=50)),
                ('destinatario_dependencia', models.CharField(blank=True, default='', max_length=250)),
                ('canal', models.CharField(choices=[('fisico', 'Físico'), ('correo', 'Correo electrónico'), ('digital', 'Digital')], max_length=20)),
                ('contacto_email', models.EmailField(blank=True, default='', max_length=254)),
                ('contacto_direccion', models.CharField(blank=True, default='', max_length=400)),
                ('asunto', models.CharField(max_length=500)),
                ('descripcion', models.TextField(blank=True, default='')),
                ('numero_folios', models.PositiveIntegerField(default=1)),
                ('estado', models.CharField(choices=[('radicada', 'Radicada'), ('en_tramite', 'En trámite'), ('respondida', 'Respondida'), ('cerrada', 'Cerrada'), ('archivada', 'Archivada')], default='radicada', max_length=20)),
                ('dias_habiles_respuesta', models.PositiveSmallIntegerField(choices=[(5, '5'), (10, '10'), (15, '15'), (30, '30')], default=15)),
                ('fecha_vencimiento', models.DateTimeField()),
                ('respuesta_texto', models.TextField(blank=True, default='')),
                ('fecha_respuesta', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_to', models.ForeignKey(blank=True, db_column='assigned_to_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='correspondencias_asignadas', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(blank=True, db_column='created_by_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='correspondencias_creadas', to=settings.AUTH_USER_MODEL)),
                ('entity', models.ForeignKey(db_column='entity_id', on_delete=django.db.models.deletion.CASCADE, related_name='correspondencias', to='entities.entity')),
                ('secretaria', models.ForeignKey(db_column='secretaria_id', on_delete=django.db.models.deletion.PROTECT, related_name='correspondencias', to='entities.secretaria')),
            ],
            options={
                'verbose_name': 'Correspondencia',
                'verbose_name_plural': 'Correspondencias',
                'db_table': 'correspondencia',
                'ordering': ['-fecha_radicacion', '-id'],
            },
        ),
        migrations.CreateModel(
            name='CorrespondenciaAnexo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('solicitud', 'Solicitud'), ('respuesta', 'Respuesta'), ('otro', 'Otro')], default='solicitud', max_length=20)),
                ('nombre', models.CharField(max_length=255)),
                ('b2_key', models.CharField(max_length=500)),
                ('content_type', models.CharField(blank=True, default='', max_length=120)),
                ('size', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('correspondencia', models.ForeignKey(db_column='correspondencia_id', on_delete=django.db.models.deletion.CASCADE, related_name='anexos', to='correspondencia.correspondencia')),
                ('uploaded_by', models.ForeignKey(blank=True, db_column='uploaded_by_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='correspondencia_anexos', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'correspondencia_anexos',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CorrespondenciaEvento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('creacion', 'Creación'), ('cambio_estado', 'Cambio de estado'), ('asignacion', 'Asignación'), ('anexo', 'Anexo'), ('respuesta', 'Respuesta'), ('otro', 'Otro')], max_length=30)),
                ('detalle', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(blank=True, db_column='actor_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='correspondencia_eventos', to=settings.AUTH_USER_MODEL)),
                ('correspondencia', models.ForeignKey(db_column='correspondencia_id', on_delete=django.db.models.deletion.CASCADE, related_name='eventos', to='correspondencia.correspondencia')),
            ],
            options={
                'db_table': 'correspondencia_eventos',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='correspondencia',
            index=models.Index(fields=['entity', 'fecha_radicacion'], name='corr_ent_fecha_idx'),
        ),
        migrations.AddIndex(
            model_name='correspondencia',
            index=models.Index(fields=['entity', 'estado'], name='corr_ent_estado_idx'),
        ),
        migrations.AddIndex(
            model_name='correspondencia',
            index=models.Index(fields=['entity', 'sentido'], name='corr_ent_sentido_idx'),
        ),
        migrations.AddIndex(
            model_name='correspondencia',
            index=models.Index(fields=['entity', 'secretaria'], name='corr_ent_sec_idx'),
        ),
        migrations.AddConstraint(
            model_name='correspondencia',
            constraint=models.UniqueConstraint(fields=('entity', 'numero_radicado'), name='uniq_correspondencia_entity_radicado'),
        ),
    ]
