# Generated by Django 5.1.4 on 2026-08-30 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entities', '0006_entity_secop_nits'),
    ]

    operations = [
        migrations.AddField(
            model_name='entity',
            name='enable_gestion_documental',
            field=models.BooleanField(default=False),
        ),
    ]
